app: hypermark_example

protocols:
  - protocols/http.yml

processes:
  - processes/users.yml
  - processes/accounts_riak.yml
  - processes/accounts_node.yml
  - processes/apps_zmq.yml

serializers:
  - serializers.yml

deserializers:
  - deserializers.yml

commands:
  - commands.yml

middleware:
  - middleware.yml

providers:
  - providers.yml