app: hypermark_example

resources:
  - resources/*.yml

protocols:
  - protocols/http.yml

serializers:
  - serializers.yml

deserializers:
  - deserializers.yml

processes:
  - processes.yml

middleware:
  - middleware.yml

maps:
  - maps.yml
